---
title: "Smoking datas"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
#' 
#' 
#+ exploreSmoke
smoke[1:5,c('Age','Sex','Grade','RuralUrban','Race', 'Tried_cigarette_smkg_even')]
smokeFormats[smokeFormats$colName == 'Tried_cigarette_smkg_even', ]
smoke$everSmoke = factor(smoke$Tried_cigarette_smkg_even, levels=1:2, labels=c('yes','no'))
table(smoke$Grade, smoke$Age, exclude=NULL)
table(smoke$Race, smoke$everSmoke, exclude=NULL)
smoke[1:7,c('Age','Sex','Grade','RuralUrban','Race', 'Tried_cigarette_smkg_even','C1MD_P30D_USE_hookah_wate','C1MD_P30D_USE_pipe_filled')]


#' 
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#' nine year olds look suspicious
#' get rid of missings and age 9
#+ smokeSub
smokeSub = smoke[smoke$Age != 9 & !is.na(smoke$Race) &
	!is.na(smoke$everSmoke), ]
dim(smokeSub)
#'
#' 
#+  
smokeAgg = reshape2::dcast(smokeSub,
	Age + Sex + Race + RuralUrban ~ everSmoke,
	length)
dim(smokeAgg)
smokeAgg = na.omit(smokeAgg)
dim(smokeAgg)


smokeAgg$total = smokeAgg$no + smokeAgg$yes
smokeAgg$prop = smokeAgg$yes / smokeAgg$total
smokeAgg[which(smokeAgg$Race == 'white' & 
	smokeAgg$Sex == 'M' & smokeAgg$RuralUrban == 'Urban'),]
#'
#' 
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, fig.width = 8}
#+ smokeExplPlot
Spch = c('M' = 15, 'F'=16)
Scol = RColorBrewer::brewer.pal(nlevels(smokeAgg$Race), 'Set2')
names(Scol) = levels(smokeAgg$Race)
plot(smokeAgg$Age, smokeAgg$prop, pch = Spch[as.character(smokeAgg$Sex)],
	col = Scol[as.character(smokeAgg$Race)])
legend('topleft', fill=Scol, legend=names(Scol))
legend('left', pch=Spch, legend=names(Spch))
#' 

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#' Which races smoke the least?
#' ... age is a confounder
#' ... as is urban/rural.  
#+ smokeModel 
smokeAgg$y = cbind(smokeAgg$yes, smokeAgg$no)
smokeFit = glm(y ~ Age + Sex + Race + RuralUrban, 
	family=binomial(link='logit'), data=smokeAgg)
knitr::kable(summary(smokeFit)$coef, digits=3)
#'
#' 
#' Intercept is age zero
#' center Age so intercept is age 15
#+ smokeFit2
smokeAgg$ageC = smokeAgg$Age - 15
smokeFit2 = glm(y ~ ageC + Sex + Race + RuralUrban, 
	family=binomial(link='logit'), data=smokeAgg)
knitr::kable(summary(smokeFit2)$coef, digits=3)
#'
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, fig.width = 8}
#' 
#' convert to baseline prob and odds 
#+ smokeConvert
# smokeTable = as.data.frame(summary(smokeFit2)$coef)
# smokeTable$lower = smokeTable$fit - 2*smokeTable$se.fit
# smokeTable$upper = smokeTable$fit + 2*smokeTable$se.fit
# 
# smokeOddsRatio = exp(smokeTable[,c('Estimate','lower','upper')])
# rownames(smokeOddsRatio)[1] = 'baseline prob'
# smokeOddsRatio[1,] = smokeOddsRatio[1,]/(1+smokeOddsRatio[,1])
# smokeOddsRatio
#'
#' make row names nicer
#+ newNames 
# rownames(smokeOddsRatio) = gsub("Race|RuralUrban|C$", "",
#                                 rownames(smokeOddsRatio) )
# rownames(smokeOddsRatio) = gsub("SexF","Female", 
#                                 rownames(smokeOddsRatio))
# knitr::kable(smokeOddsRatio, digits=3)
#'
#+ smokeFitted
# toPredict = smokeAgg[smokeAgg$RuralUrban == 'Urban', ]
# smokePred = as.data.frame(predict(smokeFit2, toPredict,  se.fit=TRUE))
# smokePred$lower = smokePred$fit - 2*smokePred$se.fit
# smokePred$upper = smokePred$fit + 2*smokePred$se.fit
# smokePredExp = exp(smokePred[,c('fit','lower','upper')])
# smokePredProb = smokePredExp / (1+smokePredExp)
# #'
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, fig.width = 8}
#+ plotFitted 
plot(toPredict$Age, smokePredProb$fit, 
	pch = Spch[as.character(toPredict$Sex)],
	col = Scol[as.character(toPredict$Race)],
	xlab='age', ylab='prob')
legend('topleft', fill=Scol, legend=names(Scol))
legend('left', pch=Spch, legend=names(Spch))

#'
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=6, fig.width = 8}
#' asian males with error bars
#+ plotAsian
isAsianMale = toPredict$Sex == 'M' & 
  toPredict$Race == 'asian'
matplot(
	toPredict[isAsianMale, 'Age'],
	smokePredProb[isAsianMale, 
	              c('fit','lower','upper')],
	type='l', lty=c(1,2,2), lwd=3, 
	col=c('black','grey','grey'),
	xlab='Age', ylab='prob'
	)


#' 



#+ smokeFitInt
smokeFitInt = glm(y ~ ageC * Sex * Race + RuralUrban, 
                family=binomial(link='logit'), data=smokeAgg)
knitr::kable(summary(smokeFitInt)$coef, digits=3)
#'
#'
#'
#+ smokeFittedInt
# smokePred = as.data.frame(predict(smokeFitInt, toPredict,  se.fit=TRUE))
# smokePred$lower = smokePred$fit - 2*smokePred$se.fit
# smokePred$upper = smokePred$fit + 2*smokePred$se.fit
# smokePredExp = exp(smokePred[,c('fit','lower','upper')])
# smokePredProb = smokePredExp / (1+smokePredExp)
#'
#+ plotFitted 
plot(toPredict$Age, smokePredProb$fit, 
     pch = Spch[as.character(toPredict$Sex)],
     col = Scol[as.character(toPredict$Race)],
     xlab='age', ylab='prob')
legend('topleft', fill=Scol, legend=names(Scol))
legend('left', pch=Spch, legend=names(Spch))

#'
#'
#'
#' asian males with error bars
#+ plotAsianInt
matplot(
  toPredict[isAsianMale, 'Age'],
  smokePredProb[isAsianMale, 
                c('fit','lower','upper')],
  type='l', lty=c(1,2,2), lwd=3, 
  col=c('black','grey','grey'),
  xlab='Age', ylab='prob'
)


#' 
```
