---
title: "STA442A3 Q2"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}

# install.packages('MEMSS')
# install.packages('nlme')
# install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)
# 
# install.packages("Pmisc", repos = "http://r-forge.r-project.org")
# install.packages("Hmisc")
# install.packages("magrittr") 0
# install.packages("dplyr")  

library(mapmisc)
library(magrittr)    
library(dplyr)         
library(rpart)
library(partykit)
library(knitr)
library(tidyverse)
library(faraway)
library(lme4)      
library(SMPracticals)  
library(nlme)
library(INLA)
library(Pmisc)
library(Hmisc)
library(MEMSS)
library(MASS)
library(ggplot2)
library(kableExtra)
library(expm)

```

# Heat

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

# INLA Model

heatUrl = "http://pbrown.ca/teaching/appliedstats/data/sableIsland.rds"
heatFile = tempfile(basename(heatUrl))
download.file(heatUrl, heatFile)
x = readRDS(heatFile)
x$month = as.numeric(format(x$Date, "%m"))
xSub = x[x$month %in% 5:10 & !is.na(x$Max.Temp...C.),]
weekValues = seq(min(xSub$Date), ISOdate(2060, 1, 1,
0, 0, 0, tz = "UTC"), by = "7 days")
xSub$week = cut(xSub$Date, weekValues)
xSub$weekIid = xSub$week
xSub$day = as.numeric(difftime(xSub$Date, min(weekValues),
units = "days"))
xSub$cos12 = cos(xSub$day * 2 * pi/365.25)
xSub$sin12 = sin(xSub$day * 2 * pi/365.25)
xSub$cos6 = cos(xSub$day * 2 * 2 * pi/365.25)
xSub$sin6 = sin(xSub$day * 2 * 2 * pi/365.25)
xSub$yearFac = factor(format(xSub$Date, "%Y"))
lmStart = lm(Max.Temp...C. ~ sin12 + cos12 + sin6 +
cos6, data = xSub)
startingValues = c(lmStart$fitted.values, rep(lmStart$coef[1],
nlevels(xSub$week)), rep(0, nlevels(xSub$weekIid) +
nlevels(xSub$yearFac)), lmStart$coef[-1])

mm = get("inla.models", INLA:::inla.get.inlaEnv())
if(class(mm) == 'function') mm = mm()
mm$latent$rw2$min.diff = NULL
assign("inla.models", mm, INLA:::inla.get.inlaEnv())
sableRes = INLA::inla(
Max.Temp...C. ~ 0 + sin12 + cos12 + sin6 + cos6 +
f(week, model='rw2',
constr=FALSE,
prior='pc.prec',
param = c(0.1/(52*100), 0.05)) +
f(weekIid, model='iid',
prior='pc.prec',
param = c(1, 0.5)) +
f(yearFac, model='iid', prior='pc.prec',
param = c(1, 0.5)),
family='T',
control.family = list(
hyper = list(
prec = list(prior='pc.prec', param=c(1, 0.5)),
dof = list(prior='pc.dof', param=c(10, 0.5)))),
control.mode = list(theta = c(-1,2,20,0,1),
x = startingValues, restart=TRUE),
control.compute=list(config = TRUE),
# control.inla = list(strategy='gaussian', int.strategy='eb'),
data = xSub, verbose=TRUE)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

a = sableRes$summary.hyper[, c(4, 3, 5)]
b = sableRes$summary.fixed[, c(4, 3, 5)]
# Pmisc::priorPost(sableRes)$summary[, c(1, 3, 5)]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

mySample = inla.posterior.sample(n = 24, result = sableRes,
num.threads = 8, selection = list(week = seq(1,
nrow(sableRes$summary.random$week))))
length(mySample)
names(mySample[[1]])
weekSample = do.call(cbind, lapply(mySample, function(xx) xx$latent))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

forAxis = ISOdate(2016:2020, 1, 1, tz = "UTC")
plot(x$Date, x$Max.Temp...C., xlim = range(forAxis),
xlab = "time", ylab = "degrees C", col = "red",
xaxt = "n")
points(xSub$Date, xSub$Max.Temp...C.)
axis(1, forAxis, format(forAxis, "%Y"))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

matplot(weekValues[-1], sableRes$summary.random$week[,
paste0(c(0.5, 0.025, 0.975), "quant")], type = "l",
lty = c(1, 2, 2), xlab = "time", ylab = "degrees C",
# xlim = ISOdate(c(1990,2025), 1, 1, tz = "UTC"),
xaxt = "n", col = "black", xaxs = "i")
forXaxis2 = ISOdate(seq(1880, 2052, by = 20), 1, 1,
tz = "UTC")
axis(1, forXaxis2, format(forXaxis2, "%Y"))
myCol = mapmisc::colourScale(NA, breaks = 1:8, style = "unique",
col = "Set2", opacity = 0.3)$col
abline(v = ISOdate(2019, 1, 1, tz = "UTC"), col = "blue")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

forXaxis2 = ISOdate(seq(1880, 2040, by = 20), 1, 1,
tz = "UTC")
matplot(weekValues[-1], weekSample, type = "l", lty = 1,
col = "#FF000050", xlab = "Time", ylab = "Degrees C",
# xlim = ISOdate(c(1880,2052), 1, 1, tz = "UTC"),
xaxt = "n", xaxs = "i", main = "Plot of posterior sample")
matlines(weekValues[-1], sableRes$summary.random$week[,
paste0(c(0.5, 0.025, 0.975), "quant")], type = "l", lwd = 1,
lty = c(1, 2, 2), col = "black")
axis(1, forXaxis2, format(forXaxis2, "%Y"))
legend("topleft", bty = "n", lty = c(1,2,1,1,1),
col = c("black", "black", "red", "blue","purple","darkred"), legend = c("mean",
"quantiles", "samples", "2019","2030","2052"))
abline(v = ISOdate(2019, 1, 1, tz = "UTC"), col = "blue")
abline(v = ISOdate(2030, 1, 1, tz = "UTC"), col = "purple")
abline(v = ISOdate(2052, 1, 1, tz = "UTC"), col = "darkred")


matplot(weekValues[-1], weekSample, type = "l", lty = 1,
col = "#FF000050", xlab = "Time", ylab = "Degrees C",
xlim = ISOdate(c(2000,2060), 1, 1, tz = "UTC"),
xaxt = "n", xaxs = "i", main = "Plot of posterior sample - zoomed")
matlines(weekValues[-1], sableRes$summary.random$week[,
paste0(c(0.5, 0.025, 0.975), "quant")], type = "l", lwd = 1,
lty = c(1, 2, 2), col = "black")
axis(1, forXaxis2, format(forXaxis2, "%Y"))
legend("topleft", bty = "n", lty = c(1,2,1,1,1),
col = c("black", "black", "red", "blue","purple","darkred"), legend = c("mean",
"quantiles", "samples", "2019","2030","2052"))
abline(v = ISOdate(2019, 1, 1, tz = "UTC"), col = "blue")
abline(v = ISOdate(2030, 1, 1, tz = "UTC"), col = "purple")
abline(v = ISOdate(2052, 1, 1, tz = "UTC"), col = "darkred")

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=4}
# Plot

temp_not_na = xSub$Max.Temp...C. %>% na.omit()
mean_temp = mean(temp_not_na)
sd_temp = sd(temp_not_na)
xSub$xRescale = (xSub$Max.Temp...C.-mean_temp)/sd_temp

ggplot(xSub, aes(x=xRescale)) +
  geom_bar(binwidth = 0.5, colour="black", fill="white",aes(y=..density..)) +
  stat_function(fun = dt, args = list(df = 10), colour="red",fill="red", geom="ribbon", alpha=0.2,  mapping = aes(ymin=0,ymax=..y..)) + 
  labs(title="T density fit to Heat data") +
                labs(x="Degrees (Normalized)", y="Density")+
  theme(plot.title=element_text(size=13,
                                    hjust=0.5,
                                    lineheight=1.2))

```

